[package]
name = "zst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
the_assoc_ty_ext = "0.1.0"
const_trait_impl = { path = "../const_trait_impl" }

[features]
structural_match = []